name: dawn_note
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.2 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/dawn_note/assets/images/image41.png
    - packages/dawn_note/assets/images/icons85010.png
    - packages/dawn_note/assets/images/arrow1.svg
    - packages/dawn_note/assets/images/kakaotalkimage20220505031711.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032022.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032152.png
    - packages/dawn_note/assets/images/icons8return481.png
    - packages/dawn_note/assets/images/icons8return482.png
    - packages/dawn_note/assets/images/icons8art642.png
    - packages/dawn_note/assets/images/icons8erase501.png
    - packages/dawn_note/assets/images/icons8pen641.png
    - packages/dawn_note/assets/images/icons8text961.png
    - packages/dawn_note/assets/images/icons8chiseltipmarker1002.png
    - packages/dawn_note/assets/images/icons8inactivestate901.png
    - packages/dawn_note/assets/images/icons8509.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032218.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032249.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032558.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032652.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032728.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505032812.png
    - packages/dawn_note/assets/images/kakaotalkphoto20220505031856.png
    - packages/dawn_note/assets/images/image42.png
    - packages/dawn_note/assets/images/image43.png
    - packages/dawn_note/assets/images/image48.png
    - packages/dawn_note/assets/images/image47.png
    - packages/dawn_note/assets/images/image49.png
    - packages/dawn_note/assets/images/image50.png
    - packages/dawn_note/assets/images/icons8508.png
    - packages/dawn_note/assets/images/image51.png
    - packages/dawn_note/assets/images/image52.png
    - packages/dawn_note/assets/images/image53.png
    - packages/dawn_note/assets/images/image54.png
    - packages/dawn_note/assets/images/image03.png
    - packages/dawn_note/assets/images/image13.png
    - packages/dawn_note/assets/images/icons8505.png
    - packages/dawn_note/assets/images/image22.png
    - packages/dawn_note/assets/images/rectangle31.svg
    - packages/dawn_note/assets/images/icons8506.png
    - packages/dawn_note/assets/images/image44.png
    - packages/dawn_note/assets/images/image45.png
    - packages/dawn_note/assets/images/image46.png
    - packages/dawn_note/assets/images/icons8507.png
    - packages/dawn_note/assets/images/image01.png
    - packages/dawn_note/assets/images/image11.png
    - packages/dawn_note/assets/images/image21.png
    - packages/dawn_note/assets/images/image31.png
    - packages/dawn_note/assets/images/icons8503.png
    - packages/dawn_note/assets/images/kakaotalk202205031938466221.png
    - packages/dawn_note/assets/images/kakaotalk20220503193846622011.png
    - packages/dawn_note/assets/images/icons85011.png
    - packages/dawn_note/assets/images/kakaotalk202205032013593071.png
    - packages/dawn_note/assets/images/kakaotalk20220503201359307011.png
    - packages/dawn_note/assets/images/kakaotalk202205032021507121.png
    - packages/dawn_note/assets/images/kakaotalk20220503202150712011.png
    - packages/dawn_note/assets/images/image56.png
    - packages/dawn_note/assets/images/image55.png
    - packages/dawn_note/assets/images/icons8904.png
    - packages/dawn_note/assets/images/ellipse2.png
    - packages/dawn_note/assets/images/ellipse1.png
    - packages/dawn_note/assets/images/icons8501.png
    - packages/dawn_note/assets/images/icons8moonsymbol602.png
    - packages/dawn_note/assets/images/icons8paper641.png
    - packages/dawn_note/assets/images/icons85005.png
    - packages/dawn_note/assets/images/icons85001.png
    - packages/dawn_note/assets/images/icons85003.png
    - packages/dawn_note/assets/images/icons85004.png
    - packages/dawn_note/assets/images/image57.png
    - packages/dawn_note/assets/images/icons8901.png
    - packages/dawn_note/assets/images/image58.png
    - packages/dawn_note/assets/images/image59.png
    - packages/dawn_note/assets/images/image60.png
    - packages/dawn_note/assets/images/image61.png
    - packages/dawn_note/assets/images/image62.png
    - packages/dawn_note/assets/images/image63.png
    - packages/dawn_note/assets/images/image64.png
    - packages/dawn_note/assets/images/icons8905.png
    - packages/dawn_note/assets/images/kakaotalk202205031938466222.png
    - packages/dawn_note/assets/images/kakaotalk202205032013593072.png
    - packages/dawn_note/assets/images/kakaotalk202205032021507122.png
    - packages/dawn_note/assets/images/icons8902.png
    - packages/dawn_note/assets/images/icons8903.png
    - packages/dawn_note/assets/images/image71.png
    - packages/dawn_note/assets/images/icons8906.png
    - packages/dawn_note/assets/images/vector1.svg
    - packages/dawn_note/assets/images/image66.png
    - packages/dawn_note/assets/images/vector2.svg
    - packages/dawn_note/assets/images/vector3.svg
    - packages/dawn_note/assets/images/kakaotalk202205031938466223.png
    - packages/dawn_note/assets/images/kakaotalk202205032013593073.png
    - packages/dawn_note/assets/images/kakaotalk202205032021507123.png
    - packages/dawn_note/assets/images/image68.png
    - packages/dawn_note/assets/images/frame60.svg
    - packages/dawn_note/assets/images/image69.png
    - packages/dawn_note/assets/images/image67.png
    - packages/dawn_note/assets/images/icons8504.png
    - packages/dawn_note/assets/images/icons85006.png
    - packages/dawn_note/assets/images/icons8paper642.png
    - packages/dawn_note/assets/images/2022051134302.png
    - packages/dawn_note/assets/images/icons85002.png
    - packages/dawn_note/assets/images/2022051134547.png
    - packages/dawn_note/assets/images/image70.png
    - packages/dawn_note/assets/images/image81.png
    - packages/dawn_note/assets/images/image91.png
    - packages/dawn_note/assets/images/icons8moonsymbol601.png
    - packages/dawn_note/assets/images/icons8return483.png
    - packages/dawn_note/assets/images/icons8return484.png
    - packages/dawn_note/assets/images/icons8art643.png
    - packages/dawn_note/assets/images/icons8erase502.png
    - packages/dawn_note/assets/images/icons8pen642.png
    - packages/dawn_note/assets/images/icons8text962.png
    - packages/dawn_note/assets/images/icons8chiseltipmarker1003.png
    - packages/dawn_note/assets/images/icons8inactivestate902.png
    - packages/dawn_note/assets/images/image02.png
    - packages/dawn_note/assets/images/image12.png
    - packages/dawn_note/assets/images/rectangle4.svg
    - packages/dawn_note/assets/images/image10.png
    - packages/dawn_note/assets/images/image14.png
    - packages/dawn_note/assets/images/image40.png
    - packages/dawn_note/assets/images/image39.png
    - packages/dawn_note/assets/images/image38.png
    - packages/dawn_note/assets/images/image37.png
    - packages/dawn_note/assets/images/image36.png
    - packages/dawn_note/assets/images/image33.png
    - packages/dawn_note/assets/images/image32.png
    - packages/dawn_note/assets/images/image35.png
    - packages/dawn_note/assets/images/image27.png
    - packages/dawn_note/assets/images/image28.png
    - packages/dawn_note/assets/images/image29.png
    - packages/dawn_note/assets/images/image30.png
    - packages/dawn_note/assets/images/image34.png
    - packages/dawn_note/assets/images/image25.png
    - packages/dawn_note/assets/images/image26.png
    - packages/dawn_note/assets/images/image17.png
    - packages/dawn_note/assets/images/image20.png
    - packages/dawn_note/assets/images/image23.png
    - packages/dawn_note/assets/images/image24.png
